#!/usr/bin/env zsh -f

cd ${0:A:h} && source ../link.zsh

################################################################################

for src in ./.*(.); do
    [[ $src -ef ./.DS_Store ]] && continue

    symlink_home $src
done
