#!/usr/bin/env zsh -f

cd ${0:A:h} && source ../link.zsh

integer -r YEAR=2026

function symlink_ {
    symlink $1 ~LIBRARY_DIR/Preferences/Autodesk/maya/$2/$1
}

################################################################################

symlink_ Maya.env       $YEAR
symlink_ myRigging.json ${YEAR}/prefs/workspaces
symlink_ userSetup.py   scripts
